# server configuration
[Server]
RunMode = "debug"
HTTPPort = 4230
ReadTimeout = 15
WriteTimeout = 15

# database connect configuration
[Database]
Type = "mysql"
User = "root"
Password = "X*TnVEzbKMwHLJ3"
Host = "127.0.0.1:3306"
Name = "acmer"
TablePrefix = "acmer_"
MaxIdleConns = 10
MaxOpenConns = 100

# jwt configuration
[Jwt]
Secret = "f^kAr7nF9VpaqM"
LongExpiresTime = 168          # hours
ShortExpiresTime = 3           # hours
Issuer = "acmer-manage-system"

# # zap logger configuration
# [zap]
# level = "info"
# format = "console"
# prefix = "[github.com/zilanlann/acmer-manage-system/server]"
# director = "log"
# show-line = true
# encode-level = "LowercaseColorLevelEncoder"
# stacktrace-key = "stacktrace"
# log-in-console = true
