definitions:
  api.auth:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  app.Response:
    properties:
      code:
        type: integer
      message:
        type: string
      result: {}
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      parameters:
      - description: 用户登录信息
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/api.auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Login
  /register:
    post:
      parameters:
      - description: userName
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Register
swagger: "2.0"
