version: "3.7"
services:
  mysql:
    container_name: ams-mysql
    image: mysql:latest
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "X*TnVEzbKMwHLJ3"
      MYSQL_DATABASE: "ams"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    restart: "always"
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    image: zilanlann/ams-server:latest
    restart: "always"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 4230:4230
    volumes:
      - ./conf/config.toml:/conf/config.toml
      - ./conf/model.conf:/conf/model.conf
      - server_log:/log
    networks:
      - backend

volumes:
  mysql_data:
  redis_data:
  server_log:

networks:
  backend:
    name: ams-backend
